import 'package:hive/hive.dart';

// This file is generated by:  dart run build_runner build
// (a ready-made copy is already included, see note.g.dart)
part 'note.g.dart';

/// The data model stored in Hive.
/// typeId must be unique for every model in the app.
@HiveType(typeId: 0)
class Note extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String content;

  @HiveField(3)
  DateTime createdAt;

  @HiveField(4)
  bool isPinned;

  Note({
    required this.id,
    required this.title,
    required this.content,
    required this.createdAt,
    this.isPinned = false,
  });
}
